/*
 * tools/make_key -- build-time device-key seed injector.
 *
 * Host program (built normally, no sanitizer variants). Given a seed on the
 * command line, it derives the 32-byte device key via dtl_kdf_derive (to record
 * it for reference) and writes a generated C header, dtl_seed.h, that embeds the
 * seed bytes:
 *
 *     static const uint8_t DTL_BUILD_SEED[] = { ... };
 *     #define DTL_BUILD_SEED_LEN <n>
 *
 * The runtime keystore is initialised from DTL_BUILD_SEED, so the device key is
 * a deterministic function of the build seed and never a hardcoded constant.
 *
 * Usage: make_key [--hex] <seed> <out-header-path>
 *   default: <seed> is used as raw string bytes
 *   --hex  : <seed> is an even-length hex string
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "crypto/kdf.h"

#define MAKE_KEY_MAX_SEED 4096u

static int hexval(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

static int parse_hex(const char *s, uint8_t *out, size_t cap, size_t *out_len)
{
    size_t n = strlen(s);
    size_t bytes;
    size_t i;

    if (n % 2 != 0)
        return -1;
    bytes = n / 2;
    if (bytes > cap)
        return -1;
    for (i = 0; i < bytes; i++) {
        int hi = hexval(s[2 * i]);
        int lo = hexval(s[2 * i + 1]);
        if (hi < 0 || lo < 0)
            return -1;
        out[i] = (uint8_t)((hi << 4) | lo);
    }
    *out_len = bytes;
    return 0;
}

int main(int argc, char **argv)
{
    int use_hex = 0;
    int ai = 1;
    const char *seed_arg;
    const char *out_path;
    uint8_t seed[MAKE_KEY_MAX_SEED];
    size_t seed_len;
    uint8_t key[32];
    size_t i;
    FILE *f;

    if (argc >= 2 && strcmp(argv[1], "--hex") == 0) {
        use_hex = 1;
        ai = 2;
    }
    if (argc != ai + 2) {
        fprintf(stderr, "usage: make_key [--hex] <seed> <out-header-path>\n");
        return 2;
    }
    seed_arg = argv[ai];
    out_path = argv[ai + 1];

    if (use_hex) {
        if (parse_hex(seed_arg, seed, sizeof seed, &seed_len) != 0) {
            fprintf(stderr, "make_key: invalid hex seed\n");
            return 2;
        }
    } else {
        seed_len = strlen(seed_arg);
        if (seed_len > sizeof seed) {
            fprintf(stderr, "make_key: seed too long\n");
            return 2;
        }
        memcpy(seed, seed_arg, seed_len);
    }
    if (seed_len == 0) {
        fprintf(stderr, "make_key: empty seed\n");
        return 2;
    }

    dtl_kdf_derive(seed, seed_len, key);

    f = fopen(out_path, "w");
    if (f == NULL) {
        fprintf(stderr, "make_key: cannot write %s\n", out_path);
        return 1;
    }

    fprintf(f, "/* Auto-generated by tools/make_key -- do not edit. */\n");
    fprintf(f, "/* device key = ");
    for (i = 0; i < 32; i++)
        fprintf(f, "%02x", key[i]);
    fprintf(f, " */\n");
    fprintf(f, "#ifndef DTL_SEED_H\n#define DTL_SEED_H\n#include <stdint.h>\n\n");
    fprintf(f, "static const uint8_t DTL_BUILD_SEED[] = {");
    for (i = 0; i < seed_len; i++) {
        if (i % 12u == 0)
            fprintf(f, "\n    ");
        fprintf(f, "0x%02x,", seed[i]);
        if (i % 12u != 11u && i + 1 < seed_len)
            fprintf(f, " ");
    }
    fprintf(f, "\n};\n#define DTL_BUILD_SEED_LEN %zuu\n\n", seed_len);
    fprintf(f, "#endif /* DTL_SEED_H */\n");

    fclose(f);
    return 0;
}
